---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.6-bullseye

inputs:
  - name: dp-observation-extractor

outputs:
  - name: build

run:
  path: dp-observation-extractor/ci/scripts/build.sh